# Generated by Django 2.2.6 on 2020-01-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('pet_breed', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('age', models.SmallIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('type_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='p_library.AnimalType')),
            ],
        ),
    ]
