# Generated by Django 2.2.6 on 2020-01-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='type_pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='type_pet',
            field=models.ManyToManyField(related_name='pet', to='p_library.AnimalType'),
        ),
    ]
