# Generated by Django 2.2.6 on 2020-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200118_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.ManyToManyField(related_name='sex', to='p_library.AnimalSex'),
        ),
    ]
