# Generated by Django 2.2.6 on 2020-01-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200118_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sex', to='p_library.AnimalSex'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type_pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='type_pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type_pet', to='p_library.AnimalType'),
            preserve_default=False,
        ),
    ]
